# init.ps1 — bring up the Ada observability stack in 1 key
# on Windows. Mirrors init.sh for Linux/macOS.
#
# Usage (from repo root):
#   pwsh -File observability/scripts/init.ps1
#
# Or from a regular PowerShell prompt:
#   .\observability\scripts\init.ps1
#
# The script is idempotent: re-running it after the stack
# is up is safe; it will pull newer images and recreate
# any containers whose config has drifted.

$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ComposeFile = Join-Path $ScriptDir '..\docker-compose.yml'
$ComposeDir = Split-Path -Parent $ComposeFile

# ---------------------------------------------------------------------
# 1. prerequisites
# ---------------------------------------------------------------------
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Error "docker is not on PATH. Install Docker Desktop 4.20+ and retry."
    exit 1
}

try {
    docker compose version | Out-Null
} catch {
    Write-Error "'docker compose' plugin missing. Update Docker Desktop to 4.20+."
    exit 1
}

# ---------------------------------------------------------------------
# 2. .env bootstrap
# ---------------------------------------------------------------------
$EnvFile = Join-Path $ComposeDir '.env'
if (-not (Test-Path -Path $EnvFile -PathType Leaf)) {
    Write-Host "INFO: writing .env with safe defaults (edit before production)"
    @'
# Generated by init.ps1 on first run. Edit before going to prod.
GRAFANA_ADMIN_USER=ada
GRAFANA_ADMIN_PASSWORD=ada
POSTGRES_USER=ada
POSTGRES_PASSWORD=ada
POSTGRES_DB=ada
'@ | Set-Content -Path $EnvFile -Encoding UTF8
}

# ---------------------------------------------------------------------
# 3. pull
# ---------------------------------------------------------------------
Write-Host '==> pulling images'
docker compose -f $ComposeFile pull

# ---------------------------------------------------------------------
# 4. up
# ---------------------------------------------------------------------
Write-Host '==> starting stack'
docker compose -f $ComposeFile up -d

# ---------------------------------------------------------------------
# 5. wait for healthchecks (max 60s)
# ---------------------------------------------------------------------
Write-Host '==> waiting for healthchecks (max 60s)'
$services = @('prometheus', 'loki', 'grafana')
foreach ($svc in $services) {
    $name = "ada-$svc"
    Write-Host -NoNewline "    $svc: "
    $healthy = $false
    for ($i = 0; $i -lt 30; $i++) {
        $status = docker inspect -f '{{.State.Health.Status}}' $name 2>$null
        if ($status -eq 'healthy') {
            Write-Host 'healthy'
            $healthy = $true
            break
        }
        Start-Sleep -Seconds 2
    }
    if (-not $healthy) {
        Write-Host "NOT healthy (status=$status) — continuing anyway"
    }
}

# ---------------------------------------------------------------------
# 6. print URLs
# ---------------------------------------------------------------------
@"

==> Ada observability stack is up.

    Grafana      http://localhost:3000     (user: from .env)
    Prometheus   http://localhost:9090
    Loki         http://localhost:3100     (no UI; query via Grafana)
    Jaeger UI    http://localhost:16686
    OTLP gRPC    localhost:4317            (push metrics / logs / traces here)

    Validate:
        curl -sf http://localhost:9090/-/healthy  ; if ($?) { "prometheus ok" }
        curl -sf http://localhost:3100/ready      ; if ($?) { "loki ok" }
        curl -sf http://localhost:16686/          ; if ($?) { "jaeger ok" }

    Stop:
        docker compose -f $ComposeFile down

"@
