#!/usr/bin/env bash
# init.sh — bring up the Ada observability stack in 1 key.
#
# Usage:
#   ./observability/scripts/init.sh
#
# Steps:
#   1. Check prerequisites (docker, docker compose plugin)
#   2. Generate a .env file with safe defaults if missing
#   3. Pull images
#   4. docker compose up -d
#   5. Wait for the 5 healthchecks to pass
#   6. Print the URLs the operator should open
#
# Linux/macOS shell. Windows users should use init.ps1.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="${SCRIPT_DIR}/../docker-compose.yml"
COMPOSE_DIR="$(dirname "${COMPOSE_FILE}")"

# ---------------------------------------------------------------------
# 1. prerequisites
# ---------------------------------------------------------------------
command -v docker >/dev/null 2>&1 || {
  echo "ERROR: docker is not on PATH. Install Docker 24+ and retry." >&2
  exit 1
}

if ! docker compose version >/dev/null 2>&1; then
  echo "ERROR: 'docker compose' plugin is missing. Install the v2 plugin." >&2
  exit 1
fi

# ---------------------------------------------------------------------
# 2. .env bootstrap
# ---------------------------------------------------------------------
if [[ ! -f "${COMPOSE_DIR}/.env" ]]; then
  echo "INFO: writing .env with safe defaults (edit before production)"
  cat >"${COMPOSE_DIR}/.env" <<'EOF'
# Generated by init.sh on first run. Edit before going to prod.
GRAFANA_ADMIN_USER=ada
GRAFANA_ADMIN_PASSWORD=ada
POSTGRES_USER=ada
POSTGRES_PASSWORD=ada
POSTGRES_DB=ada
EOF
fi

# ---------------------------------------------------------------------
# 3. pull
# ---------------------------------------------------------------------
echo "==> pulling images"
docker compose -f "${COMPOSE_FILE}" pull

# ---------------------------------------------------------------------
# 4. up
# ---------------------------------------------------------------------
echo "==> starting stack"
docker compose -f "${COMPOSE_FILE}" up -d

# ---------------------------------------------------------------------
# 5. wait for healthchecks (max 60s)
# ---------------------------------------------------------------------
echo "==> waiting for healthchecks (max 60s)"
services=(prometheus loki grafana)
for svc in "${services[@]}"; do
  echo -n "    ${svc}: "
  for _ in $(seq 1 30); do
    status=$(docker inspect -f '{{.State.Health.Status}}' "ada-${svc}" 2>/dev/null || echo "missing")
    if [[ "${status}" == "healthy" ]]; then
      echo "healthy"
      break
    fi
    sleep 2
  done
  if [[ "${status}" != "healthy" ]]; then
    echo "NOT healthy (status=${status}) — continuing anyway"
  fi
done

# ---------------------------------------------------------------------
# 6. print URLs
# ---------------------------------------------------------------------
cat <<EOF

==> Ada observability stack is up.

    Grafana      http://localhost:3000     (user: \${GRAFANA_ADMIN_USER}, password: see .env)
    Prometheus   http://localhost:9090
    Loki         http://localhost:3100     (no UI; query via Grafana)
    Jaeger UI    http://localhost:16686
    OTLP gRPC    localhost:4317            (push metrics / logs / traces here)

    Validate:
        curl -sf http://localhost:9090/-/healthy && echo "prometheus ok"
        curl -sf http://localhost:3100/ready   && echo "loki ok"
        curl -sf http://localhost:16686/       >/dev/null && echo "jaeger ok"

    Stop:
        docker compose -f "${COMPOSE_FILE}" down

EOF
